name: Docker Image CI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            instezz/teachable-school-manager:latest
            instezz/teachable-school-manager:${{ steps.get_version.outputs.VERSION }}
          #build-args: |
          #  arg1=value1
          #  arg2=value2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}